// Cards generated by the ERP contain the student code. Older cards may contain
// a JSON object with studentId, code, or id instead.
export function parseStudentCard(payload: string): string {
  if (typeof payload !== "string" || payload.length > 1024) {
    throw new Error("Invalid card. Please scan a student ID card.");
  }
  let value: unknown = payload.trim();
  try {
    const parsed: unknown = JSON.parse(value as string);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      const card = parsed as Record<string, unknown>;
      value = card.studentId ?? card.code ?? card.id;
    } else if (typeof parsed === "string") {
      value = parsed;
    } else {
      value = undefined;
    }
  } catch {
    // A plain student code is the current card format.
  }
  if (typeof value !== "string" || !/^[a-zA-Z0-9_-]{1,128}$/.test(value.trim())) {
    throw new Error("Invalid card. Please scan a student ID card.");
  }
  return value.trim();
}

export function attendanceDay(now = new Date()) {
  // Campus attendance follows India time even when the server runs in UTC.
  const date = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(now);
  const start = new Date(`${date}T00:00:00+05:30`);
  return { start, end: new Date(start.getTime() + 24 * 60 * 60 * 1000) };
}

export function attendanceTime(date: Date) {
  return date.toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", second: "2-digit" });
}

export const SCAN_COOLDOWN_SECONDS = 30;

export function createScanRequestId() {
  // getRandomValues also works for terminals served on a local HTTP network.
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}
